In [182]:
import numpy as np

In [196]:
n_actions, n_states= 2,3
dtype = np.float32

In [238]:
C = np.random.rand(n_actions, n_states, n_states).astype(dtype)
C

array([[[0.46692625, 0.01749086, 0.13599   ],
        [0.47802323, 0.98395646, 0.25724924],
        [0.46886745, 0.56317854, 0.5561447 ]],

       [[0.3522464 , 0.24508812, 0.9221939 ],
        [0.23264216, 0.05774878, 0.02448532],
        [0.02375884, 0.29980308, 0.17218387]]], dtype=float32)

In [230]:
pseudocount = 1e-3

In [186]:
T = C + pseudocount
T

array([[[0.8539275 , 0.71970177, 0.10411011, 0.23712312, 0.05855671,
         0.5781582 , 0.3120115 , 0.9137476 , 0.45268953, 0.07971621],
        [0.26017815, 0.7716645 , 0.3726572 , 0.97402585, 0.166912  ,
         0.52458185, 0.40303007, 0.8673184 , 0.7980946 , 0.75564975],
        [0.9161535 , 0.47114795, 0.03003566, 0.736102  , 0.12922753,
         0.4787043 , 0.52815956, 0.63075554, 0.9486556 , 0.33102897],
        [0.7243482 , 0.31409442, 0.2109602 , 0.6299788 , 0.24280976,
         0.391547  , 0.0687513 , 0.2616556 , 0.6103122 , 0.05807294],
        [0.26589772, 0.5330919 , 0.3616128 , 0.26255906, 0.5228387 ,
         0.36142865, 0.34873232, 0.536949  , 0.675172  , 0.90075064],
        [0.12259223, 0.4190708 , 0.1495952 , 0.29845017, 0.64713544,
         0.23133504, 0.8672484 , 0.5368683 , 0.05762762, 0.86067647],
        [0.9142782 , 0.19633022, 0.9079668 , 0.31659424, 0.6970773 ,
         0.68800443, 0.17599888, 0.8736923 , 0.46818742, 0.8729431 ],
        [0.29887405, 0.7522

In [187]:
norm = T.sum(2, keepdims=True)
norm

array([[[4.3097425],
        [5.8941126],
        [5.1999702],
        [3.5125306],
        [4.7690325],
        [4.1905994],
        [6.1110725],
        [4.2009144],
        [6.6583033],
        [7.1535206]],

       [[5.0707793],
        [5.35661  ],
        [5.251334 ],
        [3.9604607],
        [4.8795824],
        [4.7568965],
        [5.589972 ],
        [7.265041 ],
        [5.841786 ],
        [5.099254 ]],

       [[5.1268883],
        [4.6187773],
        [4.5164127],
        [4.9597588],
        [4.761673 ],
        [4.6719036],
        [3.7740006],
        [4.496336 ],
        [5.623075 ],
        [6.35319  ]],

       [[5.8026395],
        [4.600295 ],
        [5.357672 ],
        [5.6299195],
        [5.801486 ],
        [4.0652404],
        [4.750176 ],
        [4.125243 ],
        [3.7826254],
        [4.6416287]]], dtype=float32)

In [188]:
norm[norm == 0] = 1
norm

array([[[4.3097425],
        [5.8941126],
        [5.1999702],
        [3.5125306],
        [4.7690325],
        [4.1905994],
        [6.1110725],
        [4.2009144],
        [6.6583033],
        [7.1535206]],

       [[5.0707793],
        [5.35661  ],
        [5.251334 ],
        [3.9604607],
        [4.8795824],
        [4.7568965],
        [5.589972 ],
        [7.265041 ],
        [5.841786 ],
        [5.099254 ]],

       [[5.1268883],
        [4.6187773],
        [4.5164127],
        [4.9597588],
        [4.761673 ],
        [4.6719036],
        [3.7740006],
        [4.496336 ],
        [5.623075 ],
        [6.35319  ]],

       [[5.8026395],
        [4.600295 ],
        [5.357672 ],
        [5.6299195],
        [5.801486 ],
        [4.0652404],
        [4.750176 ],
        [4.125243 ],
        [3.7826254],
        [4.6416287]]], dtype=float32)

In [219]:
# C = np.random.rand(n_actions, n_states, n_states).astype(dtype)
T = C + pseudocount

norm = T.sum(2, keepdims=True)
# T /= (norm + alpha)
T /= norm
T

array([[[0.16300324, 0.41126275, 0.42573404],
        [0.14896244, 0.17364779, 0.6773898 ],
        [0.44551745, 0.18018779, 0.3742948 ]],

       [[0.31876305, 0.12913351, 0.5521034 ],
        [0.44502032, 0.1620072 , 0.39297244],
        [0.44603673, 0.4410951 , 0.11286818]]], dtype=float32)

In [220]:
T.sum(2, keepdims=True)

array([[[1.        ],
        [1.        ],
        [1.        ]],

       [[0.99999994],
        [1.        ],
        [1.        ]]], dtype=float32)

In [221]:
np.shape(T) # action, state, state

(2, 3, 3)

### suppose new state --> new dimension = n_action, n_state+1, n_state+1

#### action, state = 1, 2

In [222]:
alpha = 0.3
new_action = 1
new_state = 2
T[new_action, new_state, :] *= (1-alpha)
T.sum(2, keepdims=True)

array([[[1.        ],
        [1.        ],
        [1.        ]],

       [[0.99999994],
        [1.        ],
        [0.70000005]]], dtype=float32)

In [223]:
T = np.pad(T, ((0,0), (0,1), (0,1)), mode='constant', constant_values=pseudocount)
T

array([[[0.16300324, 0.41126275, 0.42573404, 0.001     ],
        [0.14896244, 0.17364779, 0.6773898 , 0.001     ],
        [0.44551745, 0.18018779, 0.3742948 , 0.001     ],
        [0.001     , 0.001     , 0.001     , 0.001     ]],

       [[0.31876305, 0.12913351, 0.5521034 , 0.001     ],
        [0.44502032, 0.1620072 , 0.39297244, 0.001     ],
        [0.3122257 , 0.30876657, 0.07900773, 0.001     ],
        [0.001     , 0.001     , 0.001     , 0.001     ]]], dtype=float32)

In [224]:
T[new_action, new_state, -1] = alpha
T

array([[[0.16300324, 0.41126275, 0.42573404, 0.001     ],
        [0.14896244, 0.17364779, 0.6773898 , 0.001     ],
        [0.44551745, 0.18018779, 0.3742948 , 0.001     ],
        [0.001     , 0.001     , 0.001     , 0.001     ]],

       [[0.31876305, 0.12913351, 0.5521034 , 0.001     ],
        [0.44502032, 0.1620072 , 0.39297244, 0.001     ],
        [0.3122257 , 0.30876657, 0.07900773, 0.3       ],
        [0.001     , 0.001     , 0.001     , 0.001     ]]], dtype=float32)

#### For state t+1 -> state t: initialize based on random prob

In [235]:
for action in range(n_actions):
    T[action, -1, :] = np.random.rand(len(T[action, -1, :]))
#     print(action)
T

array([[[0.16284038, 0.41085187, 0.4253087 , 0.000999  ],
        [0.14881362, 0.17347431, 0.67671305, 0.000999  ],
        [0.44507235, 0.18000777, 0.37392086, 0.000999  ],
        [0.78512996, 0.03752083, 0.60668766, 0.24709359]],

       [[0.31844464, 0.12900451, 0.5515519 , 0.000999  ],
        [0.44457573, 0.16184534, 0.39257985, 0.000999  ],
        [0.3122257 , 0.30876657, 0.07900773, 0.3       ],
        [0.7258196 , 0.66411656, 0.10328128, 0.0049198 ]]], dtype=float32)

#### Normalization

In [236]:
# T = C + pseudocount

norm = T.sum(2, keepdims=True)
# T /= (norm + alpha)
T /= norm
T

array([[[0.1628404 , 0.4108519 , 0.42530873, 0.000999  ],
        [0.14881364, 0.17347433, 0.6767131 , 0.000999  ],
        [0.44507238, 0.18000779, 0.3739209 , 0.000999  ],
        [0.4683339 , 0.02238136, 0.3618922 , 0.14739256]],

       [[0.31844464, 0.12900451, 0.5515519 , 0.000999  ],
        [0.4445758 , 0.16184536, 0.3925799 , 0.000999  ],
        [0.3122257 , 0.30876657, 0.07900773, 0.3       ],
        [0.48448136, 0.44329488, 0.0689398 , 0.00328395]]], dtype=float32)

In [237]:
T.sum(2, keepdims=True)

array([[[1.        ],
        [1.0000001 ],
        [1.        ],
        [1.        ]],

       [[1.        ],
        [1.        ],
        [1.        ],
        [0.99999994]]], dtype=float32)

In [227]:
np.random.rand()

0.4033260253502925

In [207]:
T.sum(2, keepdims=True)

array([[[1.        ],
        [1.        ],
        [1.        ],
        [0.        ]],

       [[0.99999994],
        [1.        ],
        [1.        ],
        [0.        ]]], dtype=float32)

In [180]:
# C = np.random.rand(n_actions, n_states, n_states).astype(dtype)
T = C + pseudocount

norm = T.sum(2, keepdims=True)
# T /= (norm + alpha)
T /= norm
T

array([[[1.26943678e-01, 1.22946732e-01, 1.36009440e-01, 3.10148275e-03,
         1.66895360e-01, 1.33288324e-01, 2.71091051e-02, 8.22844133e-02,
         7.23924264e-02, 1.29029050e-01],
        [8.73622820e-02, 8.35893080e-02, 1.54127523e-01, 2.66160369e-02,
         1.50129437e-01, 2.20409140e-01, 3.25349569e-02, 1.52025316e-02,
         1.24405138e-01, 1.05623662e-01],
        [1.53216749e-01, 1.29297182e-01, 4.92987111e-02, 1.59845620e-01,
         4.38706502e-02, 1.06981494e-01, 1.23775661e-01, 1.18078843e-01,
         7.57639855e-02, 3.98710445e-02],
        [3.97372060e-02, 1.39322594e-01, 1.96614563e-01, 1.44896075e-01,
         8.72240309e-03, 9.50503200e-02, 4.09535989e-02, 2.37140149e-01,
         7.29928911e-02, 2.45703142e-02],
        [1.38311148e-01, 1.18909754e-01, 8.15255418e-02, 1.12452157e-01,
         1.37720913e-01, 8.21526572e-02, 1.53612256e-01, 5.27450033e-02,
         6.94722086e-02, 5.30983508e-02],
        [6.29894063e-02, 1.81799158e-01, 6.56452104e-02, 4.4

In [181]:
T.sum(2, keepdims=True)

array([[[0.99999994],
        [1.        ],
        [0.9999999 ],
        [1.0000002 ],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.        ],
        [0.9999999 ]],

       [[0.99999994],
        [0.9999999 ],
        [1.        ],
        [0.99999994],
        [0.9999999 ],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.        ]],

       [[1.        ],
        [1.        ],
        [1.        ],
        [0.99999994],
        [0.99999994],
        [1.        ],
        [1.        ],
        [0.99999994],
        [1.        ],
        [1.        ]],

       [[0.99999994],
        [0.99999994],
        [0.99999994],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.0000001 ],
        [1.        ],
        [1.        ],
        [1.        ]]], dtype=float32)

In [ ]:
alpha = 0.1
T /= 

In [179]:
T.sum(2, keepdims=True) + (alpha / (norm+alpha))

array([[[1.0000001 ],
        [1.        ],
        [0.99999994],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.0000001 ],
        [1.        ],
        [1.        ],
        [0.99999994]],

       [[1.        ],
        [0.99999994],
        [1.0000001 ],
        [1.        ],
        [0.9999999 ],
        [0.9999999 ],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.        ]],

       [[1.        ],
        [0.9999999 ],
        [1.        ],
        [0.9999999 ],
        [0.9999999 ],
        [0.9999999 ],
        [1.        ],
        [1.        ],
        [1.        ],
        [0.99999994]],

       [[0.9999999 ],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.        ],
        [1.0000001 ],
        [1.        ],
        [1.0000001 ],
        [1.        ],
        [1.        ]]], dtype=float32)

In [139]:
# alpha = 10.0
norm = T.sum(2, keepdims=True)
T /= (norm + alpha)
T

array([[[2.93547995e-02, 3.35483663e-02, 1.79068930e-02, 3.93099673e-02,
         2.41749119e-02, 3.01362406e-02, 1.72357596e-02, 2.49713995e-02,
         6.60856720e-03, 4.30345424e-02],
        [1.48940105e-02, 2.39123963e-02, 4.72646952e-02, 5.14038056e-02,
         4.85853069e-02, 6.44262135e-03, 2.14176308e-02, 2.02820618e-02,
         9.62292950e-04, 2.62560043e-02],
        [2.65637077e-02, 2.25586239e-02, 3.77516448e-03, 3.97240371e-02,
         3.23543586e-02, 1.67122502e-02, 3.18436474e-02, 4.16227579e-02,
         2.71556973e-02, 3.18834297e-02],
        [2.06368715e-02, 8.50860495e-03, 2.92638317e-02, 5.03124930e-02,
         2.86951493e-02, 4.36403900e-02, 3.72416078e-04, 3.05090658e-02,
         3.88956480e-02, 8.67687631e-03],
        [1.54030919e-02, 4.27561775e-02, 5.87778129e-02, 1.77388918e-03,
         4.33827527e-02, 1.30027309e-02, 1.15379244e-02, 5.54103404e-03,
         3.59077635e-03, 5.05755581e-02],
        [2.60627232e-02, 2.69255321e-02, 3.16793993e-02, 7.3

In [130]:
alpha / (norm+alpha)

array([[[0.6538069 ],
        [0.67353594],
        [0.61797696],
        [0.680867  ],
        [0.725915  ],
        [0.6562394 ],
        [0.64699215],
        [0.60573995],
        [0.708635  ],
        [0.7258314 ]],

       [[0.7342434 ],
        [0.680319  ],
        [0.73421085],
        [0.63878894],
        [0.66708934],
        [0.6631412 ],
        [0.6802036 ],
        [0.7321022 ],
        [0.62459356],
        [0.69674975]],

       [[0.70387477],
        [0.6539854 ],
        [0.7028684 ],
        [0.7471334 ],
        [0.70950794],
        [0.61511356],
        [0.6528527 ],
        [0.6706075 ],
        [0.67829204],
        [0.6595244 ]],

       [[0.63361776],
        [0.6785042 ],
        [0.70020336],
        [0.65995014],
        [0.69188076],
        [0.6739538 ],
        [0.64587957],
        [0.61423266],
        [0.667298  ],
        [0.59984493]]], dtype=float32)

In [83]:
print(T.sum(2, keepdims=True))

[[[0.15868366]
  [0.16374709]
  [0.16279103]
  [0.15702443]
  [0.15710233]
  [0.14491743]
  [0.18854776]
  [0.1486464 ]
  [0.15134318]
  [0.18545514]]

 [[0.12775002]
  [0.14541796]
  [0.15551628]
  [0.1191448 ]
  [0.1384047 ]
  [0.11919104]
  [0.15163653]
  [0.14883913]
  [0.13170807]
  [0.1422598 ]]

 [[0.13694988]
  [0.1317596 ]
  [0.16746166]
  [0.14327914]
  [0.15597156]
  [0.15363795]
  [0.15043661]
  [0.1449201 ]
  [0.1588559 ]
  [0.1695481 ]]

 [[0.1335047 ]
  [0.19388327]
  [0.14123583]
  [0.1464431 ]
  [0.15730922]
  [0.13906802]
  [0.12903576]
  [0.14178851]
  [0.12194055]
  [0.13254236]]]


In [169]:
import numpy as np

# Initialize matrix size and pseudocount
n_actions = 5
n_states = 3
dtype = np.float32
pseudocount = 1e-3  # Small value to encourage new observations

# Initialize C matrix (transition counts or weights)
C = np.random.rand(n_actions, n_states, n_states).astype(dtype)

# Reserve space for new observations and normalize correctly
def update_transition_matrix(C, pseudocount, alpha=2.0):
    # Add pseudocount to encourage exploration
    T = C + pseudocount

    # Compute normalization term along the second dimension (across states)
    norm = T.sum(axis=2, keepdims=True) + alpha  # Ensure the second dimension sums to 1 with bias

    # Normalize probabilities by dividing each row-wise element by its norm
    T /= norm
    return T

# Example of expanding experiences: add new observations dynamically
def add_new_experience(C, new_state_action):
    # Expand the transition matrix to accommodate new states/actions
    new_C = np.pad(C, ((0, 0), (0, 1), (0, 1)), mode='constant', constant_values=0)

    # Update with new transition weights (e.g., based on new observation)
    action, from_state, to_state = new_state_action
    new_C[action, from_state, to_state] += 1.0  # Increment relevant transition count

    return new_C

# Update matrix with new experience
T = update_transition_matrix(C, pseudocount)
print("Initial Transition Matrix (Normalized):", T)

# Example: Add a new state-action experience and re-update matrix
new_experience = (2, 1, 3)  # action, from_state, to_state
C_expanded = add_new_experience(C, new_experience)
T_expanded = update_transition_matrix(C_expanded, pseudocount)
print("Expanded Transition Matrix (Normalized):", T_expanded)

# Check if second dimension sums to 1 for all (actions, states)
# print("Check if normalized (sums to 1):", np.allclose(T_expanded.sum(axis=1), 1.0))
print(T_expanded.sum(axis=2))


Initial Transition Matrix (Normalized): [[[0.19913459 0.19656052 0.02519968]
  [0.11963467 0.03474789 0.07677238]
  [0.22160254 0.22034426 0.06929246]]

 [[0.2689761  0.09612098 0.0268642 ]
  [0.11473124 0.1052712  0.08998868]
  [0.09245586 0.2003113  0.23046768]]

 [[0.10107278 0.04583898 0.07537883]
  [0.2411085  0.1537882  0.10619384]
  [0.15549111 0.07530739 0.0283381 ]]

 [[0.13860038 0.12788142 0.06609277]
  [0.01404892 0.25760776 0.18049309]
  [0.01408988 0.22294718 0.19797468]]

 [[0.25839746 0.15566199 0.01770097]
  [0.21765168 0.02928061 0.12472878]
  [0.23953684 0.08530906 0.18686436]]]
Expanded Transition Matrix (Normalized): [[[1.99076951e-01 1.96503624e-01 2.51923893e-02 2.89468822e-04]
  [1.19588681e-01 3.47345322e-02 7.67428726e-02 3.84274812e-04]
  [2.21548408e-01 2.20290422e-01 6.92755356e-02 2.44320690e-04]
  [4.99002053e-04 4.99002053e-04 4.99002053e-04 4.99002053e-04]]

 [[2.68894315e-01 9.60917696e-02 2.68560350e-02 3.03926994e-04]
  [1.14691667e-01 1.05234899e-01

In [64]:
import numpy as np
from scipy.stats import dirichlet, multinomial, norm, beta

class InfiniteHMM:
    def __init__(self, alpha=5.0, gamma=1.0, sigma_obs=1.0):
        self.alpha = alpha  # Concentration for transition matrix (Dirichlet Process)
        self.gamma = gamma  # Concentration for prior over states (HDP)
        self.sigma_obs = sigma_obs  # Observation noise

        self.states = []
        self.transitions = {}
        self.observations = []
        self.labels = []

    def generate_data(self, num_obs=50):
        """Generate synthetic data from a fixed HMM with infinite state space."""
        # True hidden states and corresponding observation mean values
        state_means = np.array([0.0, 2.5, 5.0])  # 3 potential states with distinct means
        state_sequence = np.random.choice(len(state_means), size=num_obs)  # State path

        self.observations = norm.rvs(loc=state_means[state_sequence], 
                                     scale=self.sigma_obs, size=num_obs)
        self.labels = state_sequence  # Store ground truth (only for comparison)

    def initialize_states(self):
        """Randomly initialize a sequence of states."""
        self.states = np.random.choice([0, 1, 2], size=len(self.observations)).tolist()

    def sample_new_state(self, obs, temp_states):
        """Gibbs sampling step: Sample a new state for a single observation."""
        unique_states = list(set(temp_states))  # Unique existing states

        # Calculate the likelihood for each existing state
        likelihoods = [
            norm.pdf(obs, loc=np.mean(self.observations[np.array(self.states) == s]),
                     scale=self.sigma_obs)
            for s in unique_states
        ]

        # Add the likelihood for a potential new state
        new_state_likelihood = norm.pdf(obs, loc=0.0, scale=self.sigma_obs)  # Prior mean 0
        likelihoods.append(new_state_likelihood)

        # Apply the gamma parameter to control the prior over new vs. existing states
        num_existing_states = len(unique_states)
        transition_probs = np.array(likelihoods) + self.gamma / (num_existing_states + 1)

        # Normalize to get probabilities
        probs = transition_probs / np.sum(transition_probs)

        # Sample a new state based on the computed probabilities
        return np.random.choice(len(probs), p=probs)


    def run_gibbs_sampling(self, num_iters=100):
        """Gibbs sampling over observations to infer state sequence."""
        for iteration in range(num_iters):
            for i, obs in enumerate(self.observations):
                # Temporarily store the current state to avoid dimension mismatch
                current_state = self.states[i]

                # Create a copy of states with the current state removed
                temp_states = self.states[:i] + self.states[i + 1:]

                # Sample a new state given the current observation
                new_state = self.sample_new_state(obs, temp_states)

                # Update the state in place
                self.states[i] = new_state

            if iteration % 10 == 0:
                print(f"Iteration {iteration}: States - {self.states}")

    def get_transition_matrix(self):
        """Construct a transition matrix from the inferred states."""
        # Get the number of unique states encountered
        unique_states = list(set(self.states))
        num_states = max(unique_states) + 1  # Ensure the matrix is large enough

        # Initialize the transition matrix with zeros
        transition_matrix = np.zeros((num_states, num_states))

        # Count transitions between inferred states
        for i in range(len(self.states) - 1):
            transition_matrix[self.states[i], self.states[i + 1]] += 1

        # Handle rows with no outgoing transitions to avoid division by zero
        with np.errstate(divide='ignore', invalid='ignore'):
            transition_matrix = (transition_matrix.T / transition_matrix.sum(axis=1)).T
            transition_matrix[np.isnan(transition_matrix)] = 0  # Replace NaNs with 0

        return transition_matrix


# Run the iHMM example
ihmm = InfiniteHMM(alpha=5.0, gamma=1.0, sigma_obs=1.0)



In [65]:
ihmm.generate_data(num_obs=30)  # Generate synthetic observations


In [66]:
ihmm.observations

array([ 5.65963615, -0.19872571,  3.50962356,  4.65908488,  5.36375053,
        5.76153194,  0.43359448, -1.20598315,  1.07504204, -0.28928466,
        3.01359196,  4.3877799 ,  1.5856051 ,  3.39165287,  4.12107144,
        4.60804084,  0.82406964,  4.18040954,  4.82832777,  2.1395342 ,
        2.14212305,  0.70935798,  5.21877393,  1.41579496,  0.10284307,
        6.11856857,  2.17842522,  5.82385691, -2.50290912,  3.98482051])

In [67]:
ihmm.labels

array([2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 1, 2, 1, 1, 2, 2, 1, 1, 2, 0, 1, 0,
       2, 1, 0, 2, 1, 2, 0, 2])

In [68]:
ihmm.initialize_states()  # Initialize random state sequence
ihmm.states

[0,
 0,
 0,
 2,
 1,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 2]

In [69]:
ihmm.run_gibbs_sampling(num_iters=500)  # Run Gibbs sampling


Iteration 0: States - [1, 1, 2, 0, 2, 3, 4, 0, 5, 4, 1, 3, 5, 2, 3, 3, 0, 2, 1, 4, 0, 2, 3, 4, 6, 3, 2, 3, 6, 3]
Iteration 10: States - [0, 1, 0, 1, 1, 1, 12, 11, 4, 12, 7, 10, 4, 0, 8, 6, 11, 1, 1, 8, 2, 9, 8, 4, 7, 9, 8, 8, 11, 4]
Iteration 20: States - [10, 10, 9, 8, 7, 1, 7, 8, 2, 0, 7, 0, 1, 4, 9, 0, 1, 10, 2, 6, 4, 10, 6, 7, 8, 5, 7, 9, 5, 9]
Iteration 30: States - [6, 3, 8, 8, 1, 7, 4, 5, 3, 2, 1, 8, 7, 7, 8, 0, 6, 7, 8, 1, 11, 10, 7, 11, 8, 3, 2, 5, 11, 7]
Iteration 40: States - [1, 9, 1, 9, 3, 7, 9, 1, 1, 7, 0, 8, 6, 4, 9, 1, 10, 0, 7, 4, 1, 9, 2, 5, 10, 3, 4, 10, 1, 0]
Iteration 50: States - [4, 9, 7, 2, 6, 0, 9, 1, 1, 8, 4, 2, 1, 8, 4, 2, 1, 3, 4, 4, 4, 9, 0, 3, 9, 2, 7, 0, 5, 10]
Iteration 60: States - [13, 7, 3, 1, 13, 0, 14, 15, 16, 0, 0, 1, 7, 3, 12, 3, 15, 2, 8, 6, 0, 5, 2, 14, 1, 12, 7, 3, 1, 7]
Iteration 70: States - [8, 7, 2, 5, 3, 2, 7, 0, 4, 0, 8, 7, 4, 7, 6, 2, 5, 0, 1, 8, 0, 3, 8, 0, 5, 5, 3, 1, 3, 6]
Iteration 80: States - [5, 6, 8, 1, 4, 4, 11, 9, 6, 5, 7, 0, 7

In [70]:
print("\nInferred Transition Matrix:")
print(ihmm.get_transition_matrix())


Inferred Transition Matrix:
[[0.         0.         0.5        0.         0.         0.
  0.         0.         0.         0.         0.5        0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         1.         0.         0.        ]
 [0.         0.         0.2        0.         0.4        0.
  0.         0.4        0.         0.         0.         0.        ]
 [0.5        0.         0.         0.         0.         0.
  0.         0.         0.5        0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         1.        ]
 [0.         0.2        0.         0.         0.2        0.
  0.2   

In [71]:
tm = ihmm.get_transition_matrix()
np.shape(tm)

(12, 12)